### ISSUE TITLE
Consider publishing to Open-VSX / VSCodium

### ISSUE THREAD

**Issue by vojtechkral** [bodil/vscode-file-browser#17]
Currently this extension is (kind of mysteriously) not visible in VSCodium.
I was a bit confused by this, see VSCodium/vscodium#514 ...
It's not really a problem for me, I just downloaded the vsix,
but I thought I'd let you know in case you wanted to have the extension available in VSCodium as well...

Thanks for making this extension!

**Comment by marcoieni** [comment]
Hi @bodil! Sorry to bother you. I am one of the maintainers of [VSpaceCode](https://github.com/VSpaceCode/VSpaceCode), which bundles the vscode-file-browser extension.

We would like to publish VSpaceCode to https://open-vsx.org/ in order to make it easier for people who use IDEs like VSCodium, Theia, etc. to install it. However, we won't be able to do it until all the extensions we bundle are published on open-vsx, too.

We already successfully published one of our bundled extension, [vscode-which-key](https://github.com/VSpaceCode/vscode-which-key) to open-vsx using a [GitHub Action](https://github.com/VSpaceCode/vscode-which-key/blob/master/.github/workflows/deploy.yml). On every tag, the extension is deployed automatically to both Visual Studio Marketplace and Open VSX.

Publishing extension to open-vsx is very simple and you can follow their [official instructions](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension).
Would you please consider this? Thanks!

**Comment by bodil** [comment]
It's actually already set up, it's just set to trigger when a release is tagged, which hasn't happened since I set it up. It's probably time for a new release, though.

**Comment by overby-me** [comment]
@bodil would you kindly tag a release? :)

**Comment by bodil** [comment]
Latest version was just published to Open-VSX.
