### ISSUE TITLE
Enhancements suggested by VSpaceCode author

### ISSUE THREAD

**Issue by codeincontext** [bodil/vscode-file-browser#2]
Hi 👋 

I'm sure you're aware of Spacemacs. Well https://github.com/VSpaceCode/VSpaceCode is a project to bring a bundle of Emacs-ey plugins to vscode, driven by a `which-key` style menu a-la Spacemacs

vscode-file-browser seems like the perfect candidate to emulate some spacemacs helm commands, so I sent it over to the maintainer (@stevenguh) and he seems excited by it. He asked about the following features:

- tab completion
- folder opening
- vscode remote support

I know you made this to scratch your personal itch, but are any of these on the roadmap, do you think they matter, and would you accept PRs to make them happen?

Honestly my personal understanding of Emacs behaviour and the boundaries between its frameworks is limited, but I'm happy to facilitate this where I can

**Comment by bodil** [comment]
Tab completion: not currently possible with the QuickPick API.

Folder opening: if you mean opening a folder as a workspace, yeah, that might be neat. If you mean opening a dired buffer or similar, Code doesn't really support that currently.

Remote support: I'm almost as surprised that it doesn't work currently as I am that I never thought to test it.

**Comment by stevenguh** [comment]
Thank you for the quick reply.

> Tab completion: not currently possible with the QuickPick API.

That makes sense. The QuickPick API is fairly limited. 

> Folder opening: if you mean opening a folder as a workspace, yeah, that might be neat. If you mean opening a dired buffer or similar, Code doesn't really support that currently.

I am thinking of opening folder as a workspace for now. It would be awesome to open a dired buffer, but I agree that the file API code exposing doesn't really give enough information to make it worth while.

> Remote support: I'm almost as surprised that it doesn't work currently as I am that I never thought to test it.

Sorry for not being more specific. This works in VSCode remote; however, the current file picker builtin to vscode remote provide a button to pick from local file, I am wondering if that would be possible.

---
I am also wondering can VSpaceCode use Extension pack feature to "bundle" this extension without changing the license since the installation process is handled by vscode. Or using this in the extension pack will require VSpaceCode to change its license to LGPL-3? Or is there a permission grant that allow us to not change license?

There are some minor issues/improvements to be more like HELM in spacemacs:
- Change the current `Ctl-A` binding to something else, because `Ctl-A` and `Ctl-E` are used to going to front and end of the text input
- Implement `Ctl+h` and `Ctl-l` for step in and out of folder. Ideally `Ctl-j/k` for going up and down the quickpick item like up and down arrow; however, I am not sure that's possible.

**Comment by bodil** [comment]
@stevenguh I strongly suspect switching from remote to local is beyond the extension API right now, but it's worth a look.

LGPL doesn't make you have to do any of that, at least if you're open source. That's just old time Microsoft FUD. 

You can rebind any part of the keymap in the normal way, see the package.json file, but I'm not sure what you'll break, if anything, if you re-enable normal cursor navigation in the input box.

**Comment by stevenguh** [comment]
> strongly suspect switching from remote to local is beyond the extension API right now, but it's worth a look.

I remembered I worked on VSCode Vim `:e` option a while back that was able to looking at files in both remote and local when the environment is in remote, so I think it's possible to an extent. Currently, this extension has a bug where the file menu will display empty content when a user opens a local file while on vscode remote (I assume it is trying looking the path in remote which doesn't exist)

> LGPL doesn't make you have to do any of that, at least if you're open source. That's just old time Microsoft FUD.

Okay. Awesome!

> You can rebind any part of the keymap in the normal way, see the package.json file, but I'm not sure what you'll break, if anything, if you re-enable normal cursor navigation in the input box.

I am wondering is there any reason you bound `Ctl-A` for this use case? I am asking because rebinding on `VSpaceCode` is a little bit more chunky.

**Comment by bodil** [comment]
I think the only thing remaining from this issue now is #6, so I'm closing this.
